# Add additional mounts needed to conform to deployment pattern
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-add-nfs-mount
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/volumes/-
    value:
      name: cas-admin
  - op: add
    path: /spec/controllerTemplate/spec/volumes/-
    value:
      name: nfs-data
      nfs:
        server: 10.5.3.132
        path: /internal-export/sas-viya/data
  - op: add
    path: /spec/controllerTemplate/spec/volumes/-
    value:
      name: nfs-homes
      nfs:
        server: 10.5.3.132
        path: /internal-export/sas-viya/homes
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/volumeMounts/-
    value:
      name: cas-admin
      mountPath: /cas/cas-admin
      readOnly: true
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/volumeMounts/-
    value:
      name: nfs-data
      mountPath: /mnt/viya-share/data
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/volumeMounts/-
    value:
      name: nfs-homes
      mountPath: /internal-export/sas-viya/homes
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
